# Generated by Django 4.2 on 2023-05-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("banquets", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customers.customer"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="banquets.location"
            ),
        ),
        migrations.AddField(
            model_name="banquetcustomerfood",
            name="banquet_customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="banquets.banquetcustomer",
            ),
        ),
        migrations.AddField(
            model_name="banquetcustomerfood",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="banquets.food"
            ),
        ),
        migrations.AddField(
            model_name="banquetcustomerentertainment",
            name="banquet_customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="banquets.banquetcustomer",
            ),
        ),
        migrations.AddField(
            model_name="banquetcustomerentertainment",
            name="entertainment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="banquets.entertainment"
            ),
        ),
        migrations.AddField(
            model_name="banquetcustomerdecoration",
            name="banquet_customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="banquets.banquetcustomer",
            ),
        ),
        migrations.AddField(
            model_name="banquetcustomerdecoration",
            name="decoration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="banquets.decoration"
            ),
        ),
        migrations.AddField(
            model_name="banquetcustomer",
            name="banquet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="banquets.banquet"
            ),
        ),
        migrations.AddField(
            model_name="banquetcustomer",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customers.customer"
            ),
        ),
        migrations.AddField(
            model_name="banquetcustomer",
            name="decoration",
            field=models.ManyToManyField(
                through="banquets.BanquetCustomerDecoration", to="banquets.decoration"
            ),
        ),
        migrations.AddField(
            model_name="banquetcustomer",
            name="entertainment",
            field=models.ManyToManyField(
                through="banquets.BanquetCustomerEntertainment",
                to="banquets.entertainment",
            ),
        ),
        migrations.AddField(
            model_name="banquetcustomer",
            name="food",
            field=models.ManyToManyField(
                through="banquets.BanquetCustomerFood", to="banquets.food"
            ),
        ),
    ]
