# Generated by Django 4.2 on 2023-04-23 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Room",
        ),
    ]
