# Generated by Django 4.2 on 2023-05-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banquets", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
