# Generated by Django 4.2 on 2023-04-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_customers_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
